# Generated by Django 4.2.24 on 2025-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
