# Generated by Django 4.2.24 on 2025-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0002_match_finalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="analysis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
