# Generated by Django 4.2.24 on 2025-11-04 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0003_match_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
