# Generated by Django 4.2.24 on 2025-11-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0004_match_update_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="update_at",
            new_name="create_at",
        ),
    ]
