# Generated by Django 4.2.24 on 2025-11-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_rename_update_at_match_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
