# Generated by Django 4.2.24 on 2025-11-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0006_rename_create_at_match_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xg_home", models.FloatField(default=0)),
                ("xg_away", models.FloatField(default=0)),
                ("possession_home", models.FloatField(default=0)),
                ("possession_away", models.FloatField(default=0)),
                ("chances_home", models.FloatField(default=0)),
                ("chances_away", models.FloatField(default=0)),
                ("shots_home", models.IntegerField(default=0)),
                ("shots_away", models.IntegerField(default=0)),
                ("shots_on_home", models.IntegerField(default=0)),
                ("shots_on_away", models.IntegerField(default=0)),
                ("corners_home", models.IntegerField(default=0)),
                ("corners_away", models.IntegerField(default=0)),
                ("fouls_home", models.IntegerField(default=0)),
                ("fouls_away", models.IntegerField(default=0)),
                ("yellow_home", models.IntegerField(default=0)),
                ("yellow_away", models.IntegerField(default=0)),
                ("score_home", models.IntegerField(blank=True, null=True)),
                ("score_away", models.IntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="jogos.match",
                        verbose_name="Partida",
                    ),
                ),
                (
                    "team_away",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_stats",
                        to="jogos.team",
                        verbose_name="Time visitante",
                    ),
                ),
                (
                    "team_home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_stats",
                        to="jogos.team",
                        verbose_name="Time mandante",
                    ),
                ),
            ],
        ),
    ]
