# Generated by Django 4.2.24 on 2025-11-09 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0007_matchstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchstats",
            name="analyzed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="danger_away",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="danger_home",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="pressure_away",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="pressure_home",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
