# Generated by Django 4.2.24 on 2025-11-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0008_matchstats_analyzed_at_matchstats_danger_away_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JogoAnaliseAoVivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_casa", models.CharField(blank=True, max_length=120, null=True)),
                ("time_casa_gol", models.IntegerField(blank=True, null=True)),
                ("time_fora", models.CharField(blank=True, max_length=120, null=True)),
                ("time_fora_gol", models.IntegerField(blank=True, null=True)),
                ("tip", models.CharField(blank=True, max_length=200, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JogoAoVivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_casa", models.CharField(blank=True, max_length=120, null=True)),
                ("time_casa_gol", models.IntegerField(blank=True, null=True)),
                ("time_fora", models.CharField(blank=True, max_length=120, null=True)),
                ("time_fora_gol", models.IntegerField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prognostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_casa", models.CharField(max_length=120)),
                ("time_fora", models.CharField(max_length=120)),
                (
                    "entrada",
                    models.CharField(
                        help_text="Tipo da aposta / mercado sugerido", max_length=200
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prognosticos",
                        to="jogos.analise",
                    ),
                ),
            ],
        ),
    ]
