# Generated by Django 4.2.24 on 2025-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0009_analise_jogoanaliseaovivo_jogoaovivo_prognostico"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JogoAnaliseAoVivo",
        ),
        migrations.DeleteModel(
            name="JogoAoVivo",
        ),
        migrations.RemoveField(
            model_name="prognostico",
            name="analise",
        ),
        migrations.DeleteModel(
            name="Analise",
        ),
        migrations.DeleteModel(
            name="Prognostico",
        ),
    ]
