# Generated by Django 4.2.24 on 2025-11-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_delete_jogoanaliseaovivo_delete_jogoaovivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_position', models.IntegerField(blank=True, null=True)),
                ('home_points', models.IntegerField(blank=True, null=True)),
                ('home_wins', models.IntegerField(blank=True, null=True)),
                ('home_draws', models.IntegerField(blank=True, null=True)),
                ('home_losses', models.IntegerField(blank=True, null=True)),
                ('home_goals_for', models.IntegerField(blank=True, null=True)),
                ('home_goals_against', models.IntegerField(blank=True, null=True)),
                ('home_goal_diff', models.CharField(blank=True, max_length=5, null=True)),
                ('home_is_top', models.BooleanField(default=False)),
                ('home_is_relegation', models.BooleanField(default=False)),
                ('away_position', models.IntegerField(blank=True, null=True)),
                ('away_points', models.IntegerField(blank=True, null=True)),
                ('away_wins', models.IntegerField(blank=True, null=True)),
                ('away_draws', models.IntegerField(blank=True, null=True)),
                ('away_losses', models.IntegerField(blank=True, null=True)),
                ('away_goals_for', models.IntegerField(blank=True, null=True)),
                ('away_goals_against', models.IntegerField(blank=True, null=True)),
                ('away_goal_diff', models.CharField(blank=True, max_length=5, null=True)),
                ('away_is_top', models.BooleanField(default=False)),
                ('away_is_relegation', models.BooleanField(default=False)),
                ('favorito', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=20)),
                ('raw_value', models.CharField(max_length=20)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('hot', models.BooleanField(default=False)),
                ('intensity', models.CharField(blank=True, max_length=20, null=True)),
                ('insight', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='chances_away',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='chances_home',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='score_away',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='score_home',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='team_away',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='team_home',
        ),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='insights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='previsao_automatica',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='jogos.match'),
        ),
        migrations.DeleteModel(
            name='TableEntry',
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
        migrations.AddField(
            model_name='teamstreak',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='jogos.match'),
        ),
        migrations.AddField(
            model_name='standingentry',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='jogos.match'),
        ),
    ]
