# Generated by Django 4.2.24 on 2025-11-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0011_standingentry_teamstreak_remove_teamstats_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='score_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='score_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_away', to='jogos.team'),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_home', to='jogos.team'),
        ),
    ]
