# Generated by Django 4.2.24 on 2025-12-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0013_match_raw_event_json_match_raw_statistics_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('xg_home', models.FloatField()),
                ('xg_away', models.FloatField()),
                ('shots_on_home', models.IntegerField()),
                ('shots_on_away', models.IntegerField()),
                ('shots_total_home', models.IntegerField()),
                ('shots_total_away', models.IntegerField()),
                ('corners_home', models.IntegerField()),
                ('corners_away', models.IntegerField()),
                ('possession_home', models.FloatField()),
                ('possession_away', models.FloatField()),
                ('touches_box_home', models.IntegerField()),
                ('touches_box_away', models.IntegerField()),
                ('final_third_entries_home', models.IntegerField()),
                ('final_third_entries_away', models.IntegerField()),
                ('momentum_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.match')),
            ],
        ),
    ]
