# Generated by Django 4.2.24 on 2025-12-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0018_runningtoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningtoday',
            name='data',
            field=models.DateField(db_index=True),
        ),
    ]
