# Generated by Django 4.2.24 on 2025-12-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0019_alter_runningtoday_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="streaks_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
