# Generated by Django 4.2.24 on 2025-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0020_match_streaks_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="analise",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
