# Generated by Django 4.2.24 on 2025-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0021_match_analise"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="sport",
            field=models.CharField(
                choices=[("football", "Football"), ("basketball", "Basketball")],
                default="football",
                max_length=20,
            ),
        ),
    ]
