# Generated by Django 4.2.24 on 2025-12-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0022_match_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="standings_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="season_ids",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
