# Generated by Django 4.2.24 on 2025-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0024_livesnapshot_assists_away_livesnapshot_assists_home_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livesnapshot",
            name="corners_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="corners_home",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="final_third_entries_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="final_third_entries_home",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="possession_away",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="possession_home",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="shots_on_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="shots_on_home",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="shots_total_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="shots_total_home",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="touches_box_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="touches_box_home",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="xg_away",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="livesnapshot",
            name="xg_home",
            field=models.FloatField(default=0),
        ),
    ]
