# Generated by Django 4.2.24 on 2025-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0025_alter_livesnapshot_corners_away_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesnapshot",
            name="points_away",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="livesnapshot",
            name="points_home",
            field=models.IntegerField(default=0),
        ),
    ]
