# Generated by Django 4.2.24 on 2025-12-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0021_match_analise"),
        ("bet", "0005_bankroll_initial_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchModelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        choices=[("v3.1", "V3.1"), ("v3.2", "V3.2")], max_length=10
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("result", "Resultado Final"),
                            ("over25", "Over 2.5"),
                            ("under25", "Under 2.5"),
                            ("btts", "BTTS"),
                            ("first_goal", "Primeiro Gol"),
                            ("corners_over10", "Escanteios Over 10.5"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("hit", "Hit"),
                            ("miss", "Miss"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True,
                        help_text="Probabilidade prevista pelo modelo para este mercado",
                        null=True,
                    ),
                ),
                (
                    "real_value",
                    models.CharField(
                        help_text="Resultado real do mercado (ex: over, under, home, away)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_evaluations",
                        to="jogos.match",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["model_version", "market"],
                        name="bet_matchmo_model_v_d11a08_idx",
                    ),
                    models.Index(
                        fields=["market", "result"],
                        name="bet_matchmo_market_41dd75_idx",
                    ),
                ],
                "unique_together": {("match", "model_version", "market")},
            },
        ),
    ]
