# Generated by Django 4.2.24 on 2025-12-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0021_match_analise"),
        ("bet", "0006_matchmodelevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreBetDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=100)),
                ("prob_home", models.FloatField(blank=True, null=True)),
                ("prob_away", models.FloatField(blank=True, null=True)),
                ("prob_h2h", models.FloatField(blank=True, null=True)),
                ("prob_final", models.FloatField()),
                ("odd", models.FloatField()),
                ("book_prob", models.FloatField()),
                ("decision", models.BooleanField()),
                ("result", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jogos.match"
                    ),
                ),
            ],
        ),
    ]
